# -*- coding: utf-8 -*-
"""TrabM2_Robinson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpC8UtwTIzgBXnfZmZAkHk8FcTCiFfCU

### **FINAL PROJECT, MODULES 2 AND 3 - PEFA2024**

#### **NAME**: Robinson Malcon Vicente Ñañez

# **1. INVESTMENT PORTFOLIO**

#### Following a TOP-DOWN strategy, we considered it appropriate to build an investment portfolio in the Americas region, specifically with US assets. The following sectors were selected: Technology, Banks, Energy, Consumer Goods and Others. Additionally, each selected asset shows investment potential in both Technical Analysis and Fundamental Analysis.

## 1.1 Download Asset Prices ##
"""

###############################################################################
#                I. Investment Portfolios
###############################################################################
#0. PRELIMINARY CONSIDERATIONS
# Download data from Yahoo Finance (identify the tickers)
# Apply the TOP-DOWN strategy (Region/Countries/Sectors)
# Investment policy
# Build a diversified portfolio
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# 1. Asset selection
tickers = ['AAPL', 'AMZN', 'WMT', 'JPM', 'GS', 'MSFT','JCI','KO','AZN','PG','XOM','HAS','CVX'] #1. Change (10-15)

# 2. Download prices and compute log returns
start_date = '2019-09-25'  #Change start date
end_date = '2024-09-25'    #Change end date
data = yf.download(tickers, start=start_date, end=end_date)['Close']
returns = np.log(data / data.shift(1)).dropna()

"""## 1.2. Portfolio Optimization ##"""

def portfolio_metrics(weights, mean_returns, cov_matrix, risk_free_rate=0.01):
    # Calculation of expected return and risk
    portfolio_return = np.sum(mean_returns * weights) * 252
    portfolio_stddev = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights))) * np.sqrt(252)
    sharpe_ratio = (portfolio_return - risk_free_rate) / portfolio_stddev
    return portfolio_return, portfolio_stddev, sharpe_ratio

def neg_sharpe_ratio(weights, mean_returns, cov_matrix, risk_free_rate=0.01):
    # We minimize the negative Sharpe ratio
    return -portfolio_metrics(weights, mean_returns, cov_matrix, risk_free_rate)[2]

def get_optimal_portfolio(mean_returns, cov_matrix, num_assets, sector_limits):
    # Constraints: no short selling and no more than 25% in a sector
    bounds = tuple((0, sector_limits) for _ in range(num_assets))
    constraints = {'type': 'eq', 'fun': lambda x: np.sum(x) - 1}
    result = minimize(neg_sharpe_ratio, num_assets*[1./num_assets], args=(mean_returns, cov_matrix),
                      method='SLSQP', bounds=bounds, constraints=constraints)
    return result.x

# Statistical data of the assets
mean_returns = returns.mean()
cov_matrix = returns.cov()
num_assets = len(tickers)

# Constraint of no more than 35% in each sector
sector_limits = 0.3130
#ADD MORE LIMITS

# Optimal portfolio calculation
optimal_weights = get_optimal_portfolio(mean_returns, cov_matrix, num_assets, sector_limits)

# 4. Portfolio metrics
portfolio_return, portfolio_risk, sharpe_ratio = portfolio_metrics(optimal_weights, mean_returns, cov_matrix)
print(f"Expected return: {portfolio_return}")
print(f"Risk (Volatility): {portfolio_risk}")
print(f"Sharpe ratio: {sharpe_ratio}")

"""## 1.3. Results Analysis ##

"""

# Comparison with the S&P 500
sp500 = yf.download('^GSPC', start=start_date, end=end_date)['Close']
sp500_returns = np.log(sp500 / sp500.shift(1)).dropna()
sp500_cumulative_return = np.exp(sp500_returns.cumsum()) - 1

# Cumulative return visualization
portfolio_cumulative_return = np.exp((returns @ optimal_weights).cumsum()) - 1
plt.plot(portfolio_cumulative_return, label='Portfolio')
plt.plot(sp500_cumulative_return, label='S&P 500')
plt.legend()
plt.show()

"""### 2. Risk Management in Investment Portfolios ###"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

# 1. Download historical stock data
tickers = ['AAPL', 'AMZN', 'WMT', 'JPM', 'GS', 'MSFT','JCI','KO','AZN','PG','XOM','HAS','CVX']
start_date = '2019-09-25'
end_date = '2023-09-25'
data = yf.download(tickers, start=start_date, end=end_date)['Close']
returns = np.log(data / data.shift(1)).dropna()

# 2. VaR parameters
confidence_level = 0.95
z_score = np.abs(np.percentile(returns, (1 - confidence_level) * 100))

# 3. Parametric VaR calculation for each stock
def var_parametric(returns, confidence_level=0.95):
    mean_return = returns.mean()
    std_dev = returns.std()
    z_score = 1.65 #np.abs(np.percentile(returns, (1 - confidence_level) * 100))
    var = mean_return - z_score * std_dev
    return var

# Individual Parametric VaR calculation
var_param = returns.apply(var_parametric)

# 4. VaR by Historical Simulation
def var_historical(returns, confidence_level=0.95):
    return np.percentile(returns, (1 - confidence_level) * 100)

var_hist = returns.apply(var_historical)

# 5. VaR by Monte Carlo Simulation
def var_montecarlo(returns, confidence_level=0.95, simulations=10000):
    mean_return = returns.mean()
    std_dev = returns.std()
    simulated_returns = np.random.normal(mean_return, std_dev, simulations)
    return np.percentile(simulated_returns, (1 - confidence_level) * 100)

var_mc = returns.apply(var_montecarlo)

# 6. CVaR calculation for each method
def cvar_historical(returns, var_value):
    return returns[returns < var_value].mean()

cvar_hist = returns.apply(lambda r: cvar_historical(r, var_historical(r)))

# 7. Portfolio VaR and CVaR
weights = optimal_weights
#weights = np.array([0.15, 0.15, 0.1, 0.2, 0.2, 0.2])  # Weight allocation
portfolio_returns = returns.dot(weights)

# Portfolio VaR using the three methods
var_param_portfolio = var_parametric(portfolio_returns)
var_hist_portfolio = var_historical(portfolio_returns)
var_mc_portfolio = var_montecarlo(portfolio_returns)

# Portfolio CVaR using the historical method
cvar_hist_portfolio = cvar_historical(portfolio_returns, var_hist_portfolio)

# 8. Marginal, Component and Incremental VaR
def marginal_var(returns, portfolio_returns, weights, confidence_level=0.95):
    marginal_vars = []
    for i in range(len(weights)):
        marginal_var = var_parametric(returns.iloc[:, i]) * weights[i]
        marginal_vars.append(marginal_var)
    return marginal_vars

marginal_var_vals = marginal_var(returns, portfolio_returns, weights)

# 9. Risk composition chart
components = pd.DataFrame({
    'Parametric VaR': var_param,
    'Historical VaR': var_hist,
    'Monte Carlo VaR': var_mc,
    'Marginal VaR': marginal_var_vals
}, index=tickers)

components.plot(kind='bar', figsize=(10, 7), title="Portfolio Risk Composition (VaR)")
plt.show()

# 10. Portfolio results
print(f"Portfolio Parametric VaR: {var_param_portfolio}")
print(f"Portfolio Historical VaR: {var_hist_portfolio}")
print(f"Portfolio Monte Carlo VaR: {var_mc_portfolio}")
#print(f"Portfolio Historical CVaR: {cvar_hist_portfolio}")

"""### 3. Risk Management in Investment Portfolios II ###"""

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# 1. Download historical data
tickers = ['AAPL', 'AMZN', 'WMT', 'JPM', 'GS', 'MSFT','JCI','KO','AZN','PG','XOM','HAS','CVX']
start_date = '2019-09-25'
end_date = '2023-09-25'
data = yf.download(tickers, start=start_date, end=end_date)['Close']
returns = np.log(data / data.shift(1)).dropna()
returns

# 2. Portfolio parameters
portfolio_value = 1_000_000
weights = np.array([0.067, 0.073, 0.069, 0.063, 0.07, 0.075, 0.075, 0.08, 0.089, 0.079, 0.085, 0.08, 0.095 ])  # Portfolio weights

# Portfolio returns calculation
portfolio_returns = returns.dot(weights)

# Portfolio Parametric VaR
confidence_level = 0.95
z_score = np.percentile(portfolio_returns, (1 - confidence_level) * 100)

def var_parametric(returns, weights, portfolio_value, confidence_level=0.95):
    mean = np.mean(returns.dot(weights))
    std_dev = np.std(returns.dot(weights))
    z = np.percentile(returns, (1 - confidence_level) * 100)
    var = portfolio_value * (mean - z * std_dev)
    return var

# 3. Component and Incremental VaR
cov_matrix = returns.cov()  # Covariance matrix of the assets
portfolio_std = np.sqrt(weights.T @ cov_matrix @ weights)  # Portfolio standard deviation
var_total = var_parametric(returns, weights, portfolio_value)

# Component VaR: Contribution of each asset to the total VaR
var_component = weights * (cov_matrix @ weights) / portfolio_std
var_component_total = var_component * portfolio_value

# Incremental VaR: Change in VaR if each asset is removed
var_incremental = var_total - (weights * var_component_total)

# 4. Component VaR chart
components = pd.DataFrame({
    'Component VaR ($)': var_component_total,
    'Incremental VaR ($)': var_incremental
}, index=tickers)

components.plot(kind='bar', figsize=(10, 7), title="Portfolio Risk Composition (Component and Incremental VaR)")
plt.show()

# 5. Backtesting
# For backtesting, we compare the number of days where the actual loss exceeds the estimated VaR.

backtest_violations = (portfolio_returns < -var_total / portfolio_value).sum()
print(f"VaR Violations (Backtesting): {backtest_violations}")

# Backtesting chart
plt.figure(figsize=(10, 6))
plt.plot(portfolio_returns.index, portfolio_returns, label='Portfolio Returns')
plt.axhline(-var_total / portfolio_value, color='red', linestyle='--', label=f'VaR ({confidence_level*100:.0f}% Confidence)')
plt.fill_between(portfolio_returns.index, -var_total / portfolio_value, portfolio_returns.min(), color='red', alpha=0.3, label='VaR Violations')
plt.legend(loc='upper right')
plt.title('VaR Backtesting: Portfolio Returns vs. VaR')
plt.show()

# 6. Stress Testing
# For stress testing, we can analyze scenarios where the market drops 10%, 20%, 30%, etc.

stress_levels = [0.1, 0.2, 0.3]  # Example stress levels
stress_var = {f'Stress {int(level * 100)}%': portfolio_value * level * portfolio_std for level in stress_levels}

# Stress Testing chart
plt.figure(figsize=(10, 6))
stress_values = list(stress_var.values())
plt.bar(stress_var.keys(), stress_values, color='orange')
plt.title('Stress Testing: VaR Impact under Different Stress Levels')
plt.ylabel('VaR ($)')
plt.show()

for level, stress_value in stress_var.items():
    print(f"{level}: VaR under stress: ${stress_value:.2f}")
